apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pxvfeg9xi-go 
  janus-idp.io/tekton: pxvfeg9xi-go
  backstage.io/kubernetes-id: pxvfeg9xi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pxvfeg9xi-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml