apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pxvfeg9xi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pxvfeg9xi-go 
  name: pxvfeg9xi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pxvfeg9xi-go 
